export const FETCH_STARTED = 'INSPIRATION/FETCH_STARTED';
export const FETCH_SUCCESS = 'INSPIRATION/FETCH_SUCCESS';
export const FETCH_FAILURE = 'INSPIRATION/FETCH_FAILURE';
export const TOGGLE_SITE = 'INSPIRATION/TOGGLE_SITE';
